version: '3.9'
services:
  postgres:
    image: postgres:12.5
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db-init.sql:/docker-entrypoint-initdb.d/db-init.sql
    env_file:
      - .database.env

volumes:
  db-data:
